"""sync schema with current models

Applies cumulative schema changes made through models without Alembic:
- BE-013: drop unused `contacts` table
- BE-019: NOT NULL on page_views.page_path and session_id
- BE-010: add indexes on page_views.created_at and session_id
- BE-007: widen page_views.ip_address to 64 chars (hashed IPs)
- BE-001: NOT NULL on projects.technologies

For existing production databases, run: alembic upgrade head
For fresh databases, Base.metadata.create_all() creates tables at current
spec; run `alembic stamp head` once to mark as already at this revision.

Revision ID: 19fd54de976f
Revises:
Create Date: 2026-04-12

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

from alembic import op  # type: ignore[attr-defined]

# revision identifiers, used by Alembic.
revision: str = "19fd54de976f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("contacts")
    op.alter_column("page_views", "page_path", existing_type=sa.VARCHAR(length=500), nullable=False)
    op.alter_column(
        "page_views",
        "ip_address",
        existing_type=sa.VARCHAR(length=45),
        type_=sa.String(length=64),
        existing_nullable=True,
    )
    op.alter_column(
        "page_views", "session_id", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.create_index(op.f("ix_page_views_created_at"), "page_views", ["created_at"], unique=False)
    op.create_index(op.f("ix_page_views_session_id"), "page_views", ["session_id"], unique=False)
    op.alter_column("projects", "technologies", existing_type=sqlite.JSON(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("projects", "technologies", existing_type=sqlite.JSON(), nullable=True)
    op.drop_index(op.f("ix_page_views_session_id"), table_name="page_views")
    op.drop_index(op.f("ix_page_views_created_at"), table_name="page_views")
    op.alter_column("page_views", "session_id", existing_type=sa.VARCHAR(length=255), nullable=True)
    op.alter_column(
        "page_views",
        "ip_address",
        existing_type=sa.String(length=64),
        type_=sa.VARCHAR(length=45),
        existing_nullable=True,
    )
    op.alter_column("page_views", "page_path", existing_type=sa.VARCHAR(length=500), nullable=True)
    op.create_table(
        "contacts",
        sa.Column("id", sa.VARCHAR(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), nullable=False),
        sa.Column("email", sa.VARCHAR(length=255), nullable=False),
        sa.Column("subject", sa.VARCHAR(length=255), nullable=True),
        sa.Column("message", sa.TEXT(), nullable=False),
        sa.Column("ip_address", sa.VARCHAR(length=45), nullable=True),
        sa.Column("user_agent", sa.TEXT(), nullable=True),
        sa.Column("status", sa.VARCHAR(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
