"""fresh baseline + close the page_views.city drift (D3-BE-04)

Two jobs, split by database state:

- EXISTING database (prod, dev, any DB with a users table): the only
  delta the migration chain never recorded is page_views.city — added to
  the model 2026-04-17 and materialised in prod by the create_all()
  bootstrap, but absent from every revision. Add it if missing, done.

- FRESH database: create the entire schema at current model spec. The
  historical revisions all early-return on fresh databases (they encode
  deltas against a legacy schema that no longer exists anywhere), so
  this revision is the sole creator on the empty path. That is what
  makes `alembic upgrade head` work from nothing — and what lets the
  drift test (tests/test_migration_drift.py) assert chain == models,
  so a model edit without a migration fails CI instead of silently
  diverging from prod.

The create_table block below is alembic-autogenerated against the
current models; regenerate rather than hand-edit if it ever needs to
change (it shouldn't — future schema changes are new revisions).

Revision ID: da9f04bf81a7
Revises: e9b1c47d2f86
Create Date: 2026-07-19

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op  # type: ignore[attr-defined]

# revision identifiers, used by Alembic.
revision: str = "da9f04bf81a7"
down_revision: str | Sequence[str] | None = "e9b1c47d2f86"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    inspector = sa.inspect(op.get_bind())

    if inspector.has_table("users"):
        # Existing database: close the one recorded-nowhere delta.
        if inspector.has_table("page_views"):
            columns = {col["name"] for col in inspector.get_columns("page_views")}
            if "city" not in columns:
                op.add_column("page_views", sa.Column("city", sa.String(length=100), nullable=True))
        return

    # Fresh database: full schema at current model spec (autogenerated).
    op.create_table(
        "companies",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("detailed_description", sa.Text(), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("logo_url", sa.String(length=500), nullable=True),
        sa.Column("website", sa.String(length=500), nullable=True),
        sa.Column("order_index", sa.Integer(), nullable=True),
        sa.Column("video_url", sa.String(length=500), nullable=True),
        sa.Column("video_title", sa.String(length=255), nullable=True),
        sa.Column("map_url", sa.String(length=500), nullable=True),
        sa.Column("map_title", sa.String(length=255), nullable=True),
        sa.Column("responsibilities", sa.JSON(), nullable=True),
        sa.Column("technologies", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_companies_order_index"), "companies", ["order_index"], unique=False)
    op.create_table(
        "documents",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("document_type", sa.String(), nullable=False),
        sa.Column("file_path", sa.String(), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("file_url", sa.String(), nullable=False),
        sa.Column("published_date", sa.String(), nullable=True),
        sa.Column("order_index", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_documents_order_index"), "documents", ["order_index"], unique=False)
    op.create_table(
        "education",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("institution", sa.String(length=200), nullable=False),
        sa.Column("degree", sa.String(length=200), nullable=False),
        sa.Column("field_of_study", sa.String(length=200), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("logo_url", sa.String(length=500), nullable=True),
        sa.Column("is_certification", sa.Boolean(), nullable=True),
        sa.Column("certificate_number", sa.String(length=100), nullable=True),
        sa.Column("certificate_url", sa.String(length=500), nullable=True),
        sa.Column("order_index", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_education_is_certification"), "education", ["is_certification"], unique=False
    )
    op.create_index(op.f("ix_education_order_index"), "education", ["order_index"], unique=False)
    op.create_table(
        "oauth_states",
        sa.Column("state", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("client_ip", sa.String(length=45), nullable=True),
        sa.PrimaryKeyConstraint("state"),
    )
    op.create_index(
        op.f("ix_oauth_states_expires_at"), "oauth_states", ["expires_at"], unique=False
    )
    op.create_table(
        "oss_contributions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("github_node_id", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("repo_name_with_owner", sa.String(length=255), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("is_draft", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("author_login", sa.String(length=255), nullable=True),
        sa.Column("bucket", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("merged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "synced_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_oss_contributions_bucket"), "oss_contributions", ["bucket"], unique=False
    )
    op.create_index(
        "ix_oss_contributions_bucket_repo_activity",
        "oss_contributions",
        ["bucket", "repo_name_with_owner", "last_activity_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_oss_contributions_github_node_id"),
        "oss_contributions",
        ["github_node_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_oss_contributions_repo_name_with_owner"),
        "oss_contributions",
        ["repo_name_with_owner"],
        unique=False,
    )
    op.create_table(
        "page_views",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("page_path", sa.String(length=500), nullable=False),
        sa.Column("referrer", sa.String(length=500), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("session_id", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_page_views_created_at"), "page_views", ["created_at"], unique=False)
    op.create_index(
        "ix_page_views_created_country", "page_views", ["created_at", "country"], unique=False
    )
    op.create_index(
        "ix_page_views_created_path", "page_views", ["created_at", "page_path"], unique=False
    )
    op.create_index(op.f("ix_page_views_session_id"), "page_views", ["session_id"], unique=False)
    op.create_table(
        "skills",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("proficiency_level", sa.Integer(), nullable=True),
        sa.Column("years_of_experience", sa.Float(), nullable=True),
        sa.Column("order_index", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_skills_order_index"), "skills", ["order_index"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("github_id", sa.String(length=20), nullable=False),
        sa.Column("username", sa.String(length=39), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column("is_admin", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_index(op.f("ix_users_github_id"), "users", ["github_id"], unique=True)
    op.create_table(
        "projects",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("detailed_description", sa.Text(), nullable=True),
        sa.Column("technologies", sa.JSON(), server_default="[]", nullable=False),
        sa.Column("github_url", sa.String(length=500), nullable=True),
        sa.Column("live_url", sa.String(length=500), nullable=True),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column("company_id", sa.String(), nullable=True),
        sa.Column("featured", sa.Boolean(), nullable=True),
        sa.Column("order_index", sa.Integer(), nullable=True),
        sa.Column("video_url", sa.String(length=500), nullable=True),
        sa.Column("video_title", sa.String(length=255), nullable=True),
        sa.Column("map_url", sa.String(length=500), nullable=True),
        sa.Column("map_title", sa.String(length=255), nullable=True),
        sa.Column("responsibilities", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_projects_company_id"), "projects", ["company_id"], unique=False)
    op.create_index(op.f("ix_projects_order_index"), "projects", ["order_index"], unique=False)
    op.create_table(
        "refresh_tokens",
        sa.Column("jti", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column(
            "issued_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("jti"),
    )
    op.create_index(
        op.f("ix_refresh_tokens_expires_at"), "refresh_tokens", ["expires_at"], unique=False
    )
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)


def downgrade() -> None:
    """Downgrade schema.

    Deliberately asymmetric: only the city column is reversed. After this
    revision runs, a fresh-created database is indistinguishable from a
    pre-existing one, and a downgrade that guessed wrong would drop every
    production table. Refusing to drop schema is the only safe inverse.
    """
    inspector = sa.inspect(op.get_bind())
    if inspector.has_table("page_views"):
        columns = {col["name"] for col in inspector.get_columns("page_views")}
        if "city" in columns:
            op.drop_column("page_views", "city")
