"""Regenerate backend/requirements-dev.txt as a hash-pinned, dev-only subset.

`uv export --extra dev` emits the FULL resolution (prod + dev). The committed
requirements-dev.txt is deliberately only the *difference*, because CI installs
requirements.txt alongside it. The subtraction is against a second export with
no extras -- NOT against requirements.txt, which is compiled for one platform
and so omits markered prod packages (uvloop) that must not be re-homed here.
uv's --hash lines are preserved so the dev install runs under --require-hashes.
"""

import re
import subprocess
import sys
from pathlib import Path

BACKEND = Path(sys.argv[1])
NAME_RE = re.compile(r"^([A-Za-z0-9._-]+)==")


def norm(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def blocks(text: str):
    """Yield (normalised_name, raw_block) for each requirement in a pip file."""
    current: list[str] = []
    name = None
    for line in text.splitlines():
        match = NAME_RE.match(line)
        if match:
            if name is not None:
                yield name, "\n".join(current)
            name, current = norm(match.group(1)), [line]
        elif name is not None:
            current.append(line)
    if name is not None:
        yield name, "\n".join(current)


def export(extra_args: list[str]) -> str:
    return subprocess.run(
        ["uv", "export", "--no-emit-project", *extra_args],
        cwd=BACKEND,
        capture_output=True,
        text=True,
        check=True,
    ).stdout


full = export(["--extra", "dev"])

prod = {name for name, _ in blocks(export([]))}
dev = [(name, block) for name, block in blocks(full) if name not in prod]

header = """# This file was autogenerated by scripts/gen-dev-requirements.py, which runs
#    uv export --extra dev --no-emit-project
# and keeps only what a no-extras export does NOT already contain.
# Dev/CI-only packages (not installed in production Docker image).
# Regenerate with: python scripts/gen-dev-requirements.py backend
# CI installs both files under --require-hashes:
#    pip install --require-hashes -r requirements.txt
#    pip install --require-hashes -r requirements-dev.txt
"""

out = header + "\n".join(block for _, block in dev) + "\n"
(BACKEND / "requirements-dev.txt").write_text(out, encoding="utf-8", newline="\n")
print(f"{len(dev)} dev-only packages written")
for name, _ in dev:
    print(" ", name)
