# Legacy Azure Static Web Apps deployment
# This file is kept for reference but the main CI/CD is now handled by ci.yml

name: Azure Static Web Apps CI/CD (Legacy)

on:
  workflow_dispatch: # Manual trigger only
  
jobs:
  legacy_deploy:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    name: Legacy Deployment
    steps:
      - uses: actions/checkout@v4

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "site"
          output_location: ""
